Delete deprecated argument
django-cms/djangocms-attributes-field pull request #42
Opened 2021-11-01 19:02 UTC by heller166

Support for context argument was [removed](https://docs.djangoproject.com/en/3.2/releases/3.0/#:~:text=Support%20for%20the%20context%20argument%20of%20Field.from_db_value()%20and%20Expression.convert_value()%20is%20removed.) in Django 3.0

2021-11-01 19:25 UTC, vinitkumar commented
@heller166 Thanks for contributing, Can you please write this code in a backward compatible way so that it doesn't break for old version of Django and works for the newer versions too?

2021-11-01 20:00 UTC, heller166 commented
I'm not sure that I can do that now that. I was trying to avoid getting a `RemovedInDjango30Warning` that is issued in the following [code](https://github.com/django/django/blob/cf63dd5c1b90d72a59dd43f1a75306fa3e11a8bf/django/db/models/sql/compiler.py#L1065-L1074). The function that is executed to check if context is present checks the method signature and I can't come up with a way for it to be removed while keeping backwards compatibility. 
```
def func_supports_parameter(func, parameter):
    return parameter in inspect.signature(func).parameters
```

2021-11-02 04:12 UTC, vinitkumar commented
@heller166 You did't had to close your pull request.


Check this code, how we can fix some deprecation warnings or errors using this conditionals, and also this:

```
from platform import python_version
from django import get_version

from distutils.version import LooseVersion


DJANGO_VERSION = get_version()
PYTHON_VERSION = python_version()

# These means "less than or equal to DJANGO_FOO_BAR"
DJANGO_2_2 = LooseVersion(DJANGO_VERSION) < LooseVersion('3.0')
DJANGO_3_0 = LooseVersion(DJANGO_VERSION) < LooseVersion('3.1')
DJANGO_3_1 = LooseVersion(DJANGO_VERSION) < LooseVersion('3.2')
DJANGO_3_2 = LooseVersion('3.2') <= LooseVersion(DJANGO_VERSION) and  LooseVersion(DJANGO_VERSION) < LooseVersion('3.3')
```

https://github.com/django-cms/django-cms/pull/7062/commits/cc394d9c2845eeff87d1350820c4cbb33157ba97#diff-5452cbe13e8c4195320b722d63a033d4670ecd0d57a3ba6772d1fd1152fd4d58L40

2021-11-02 19:17 UTC, heller166 commented
@vinitkumar thanks for the suggestion. I implemented a solution, let me know what you think. I tried to come up with some way to test this but it seemed a bit more trouble than its worth.

2021-11-10 15:28 UTC, vinitkumar requested changes

2021-11-10 15:28 UTC, vinitkumar commented on djangocms_attributes_field/fields.py
> +from cms.utils.compat import DJANGO_2_2
This file doesn't exists in the repo, just copy the same logic into a utils file and use that to import and this should be fine.

2022-03-27 20:18 UTC, marksweb commented
@vinitkumar looks like there has been some work since your comments so could you review again?

2024-11-19 05:46 UTC, vinitkumar approved these changes

2024-11-21 19:43 UTC, vinitkumar commented
@fsbraun The change looks good here. Should we merge it?

2024-11-21 19:58 UTC, marksweb commented
@vinitkumar could merge it so the author gets their contribution in and then extend it because the support brought in should be the standard now with nobody using 2.2

2024-11-22 02:13 UTC, vinitkumar commented
@marksweb Roger that.

2024-11-22 02:13 UTC, merged